import Head from "next/head";
import { UploadFilesForm } from "~/components/UploadFilesForm";
import { FilesContainer } from "~/components/FilesContainer";
import { useState, useEffect } from "react";
import { type FileProps } from "~/components/FilesContainer";

export default function Home() {
  const [files, setFiles] = useState<FileProps[]>([]);

  const fetchFiles = async () => {
    const response = await fetch("/api/files");
    const body = (await response.json()) as FileProps[];
    setFiles(body);
  };

  useEffect(() => {
    fetchFiles().catch(console.error);
  }, []);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center gap-5 font-mono">
        <UploadFilesForm onUploadSuccess={fetchFiles} />

        <FilesContainer files={files} fetchFiles={fetchFiles} />
      </main>
    </>
  );
}
